In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.datasets import load_iris

from mlp_model import MLP

In [35]:
iris_data = load_iris()
X = iris_data.data
y = iris_data.target

encoder = OneHotEncoder(sparse_output=False)
y_encoded = encoder.fit_transform(y.reshape(-1, 1))

X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, stratify=y, random_state=42)

model = MLP(input_size=4, hidden_size=5, output_size=3, learning_rate=0.001)
model.train(X_train, y_train, epochs=1000)

y_pred = model.predict(X_test)
y_pred_encoded = encoder.transform(y_pred.reshape(-1, 1))

accuracy = accuracy_score(np.argmax(y_test, axis=1), y_pred)
conf_matrix = confusion_matrix(np.argmax(y_test, axis=1), y_pred)

print(f'Accuracy: {accuracy}')
print('Confusion Matrix:')
print(conf_matrix)

Epoch 0, Cost: 1.0089
Epoch 100, Cost: 0.1461
Epoch 200, Cost: 0.1230
Epoch 300, Cost: 0.0937
Epoch 400, Cost: 0.0546
Epoch 500, Cost: 0.0391
Epoch 600, Cost: 0.0365
Epoch 700, Cost: 0.0347
Epoch 800, Cost: 0.0332
Epoch 900, Cost: 0.0321
Accuracy: 0.9666666666666667
Confusion Matrix:
[[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]
