In [30]:
# Imports
import numpy as np
from logr_model import logistic_regression_predict
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

In [31]:
# Load the iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# Split the data to meet the requirements
X_train, X_test, y_train, y_test = [], [], [], []

np.random.seed(42)

for species in range(3):
    species_indices = np.where(y == species)[0]
    X_species = X[species_indices]
    y_species = y[species_indices]
    
    train_indices = np.random.choice(len(X_species), 40, replace=False)
    test_indices = np.setdiff1d(range(len(X_species)), train_indices)[:10]
    
    X_train.extend(X_species[train_indices])
    X_test.extend(X_species[test_indices])
    y_train.extend(y_species[train_indices])
    y_test.extend(y_species[test_indices])

X_train, X_test, y_train, y_test = map(np.array, [X_train, X_test, y_train, y_test])

In [32]:
# Use our LogReg model
y_pred = logistic_regression_predict(X_train, y_train, X_test, max_iter=1000, learning_rate=0.01, type='softmax')

# Print out evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
precision = precision_score(y_test, y_pred, average='macro')
print("Precision (macro):", precision)
recall = recall_score(y_test, y_pred, average='macro')
print("Recall (macro):", recall)
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", conf_matrix)

Accuracy: 0.9666666666666667
Precision (macro): 0.9696969696969697
Recall (macro): 0.9666666666666667
Confusion Matrix:
 [[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]


In [33]:
# Scikit-learn implementation for reference
model = LogisticRegression(max_iter=1000, solver='lbfgs')

model.fit(X_train, y_train)
y_pred_sklearn = model.predict(X_test)

# Print out evaluation metrics
accuracy_sklearn = accuracy_score(y_test, y_pred_sklearn)
print("Accuracy (scikit-learn):", accuracy_sklearn)
precision_sklearn = precision_score(y_test, y_pred_sklearn, average='macro')
print("Precision (macro) (scikit-learn):", precision_sklearn)
recall_sklearn = recall_score(y_test, y_pred_sklearn, average='macro')
print("Recall (macro) (scikit-learn):", recall_sklearn)
conf_matrix_sklearn = confusion_matrix(y_test, y_pred_sklearn)
print("Confusion Matrix (scikit-learn):\n", conf_matrix_sklearn)

Accuracy (scikit-learn): 0.9666666666666667
Precision (macro) (scikit-learn): 0.9696969696969697
Recall (macro) (scikit-learn): 0.9666666666666667
Confusion Matrix (scikit-learn):
 [[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]
